name: CI/CD Pipeline For ChatApp

on:
  push:
    branches:
      - main

env:
  IMAGE_NAME: mzkpixels/realtime-chatapp
  IMAGE_TAG: ${{ github.sha }}

jobs:
  deploy:

    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Docker Login
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_TOKEN }}

      - name: Build Image
        run: |
          docker build \
            --build-arg VITE_BACKEND_URL="${{ secrets.VITE_BACKEND_URL }}" \
            --build-arg VITE_FIREBASE_API_KEY="${{ secrets.VITE_FIREBASE_API_KEY }}" \
            --build-arg VITE_FIREBASE_AUTH_DOMAIN="${{ secrets.VITE_FIREBASE_AUTH_DOMAIN }}" \
            --build-arg VITE_FIREBASE_PROJECT_ID="${{ secrets.VITE_FIREBASE_PROJECT_ID }}" \
            --build-arg VITE_FIREBASE_STORAGE_BUCKET="${{ secrets.VITE_FIREBASE_STORAGE_BUCKET }}" \
            --build-arg VITE_FIREBASE_MESSAGING_SENDER_ID="${{ secrets.VITE_FIREBASE_MESSAGING_SENDER_ID }}" \
            --build-arg VITE_FIREBASE_APP_ID="${{ secrets.VITE_FIREBASE_APP_ID }}" \
            --build-arg VITE_FIREBASE_VAPID_KEY="${{ secrets.VITE_FIREBASE_VAPID_KEY }}" \
            -t $IMAGE_NAME:latest \
            -t $IMAGE_NAME:$IMAGE_TAG \
            .

      - name: Push Image
        run: |
          docker push $IMAGE_NAME:latest
          docker push $IMAGE_NAME:$IMAGE_TAG

      - name: Deploy To VPS
        uses: appleboy/ssh-action@v1.0.3

        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          password: ${{ secrets.SSH_PASS }}

          script: |
            docker pull mzkpixels/realtime-chatapp:latest

            docker stop chatapp || true
            docker rm chatapp || true

            docker run -d \
              --name chatapp \
              --restart always \
              -p 5000:5000 \
              -e MONGO_URL="${{ secrets.MONGO_URL }}" \
              -e PORT="5000" \
              -e JWT_SECRET="${{ secrets.JWT_SECRET }}" \
              -e FRONTEND_URL="${{ secrets.FRONTEND_URL }}" \
              -e IMAGEKIT_PUBLIC_KEY="${{ secrets.IMAGEKIT_PUBLIC_KEY }}" \
              -e IMAGEKIT_PRIVATE_KEY="${{ secrets.IMAGEKIT_PRIVATE_KEY }}" \
              -e IMAGEKIT_URL_ENDPOINT="${{ secrets.IMAGEKIT_URL_ENDPOINT }}" \
              -e FIREBASE_PROJECT_ID="${{ secrets.FIREBASE_PROJECT_ID }}" \
              -e FIREBASE_PRIVATE_KEY="${{ secrets.FIREBASE_PRIVATE_KEY }}" \
              -e FIREBASE_CLIENT_EMAIL="${{ secrets.FIREBASE_CLIENT_EMAIL }}" \
              mzkpixels/realtime-chatapp:latest